name: xeus-kernels
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - xeus-r
  - numpy
  - pandas
  - scipy
  - seaborn
  - matplotlib
  - scikit-learn
