name: xeus-kernels
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - xeus-r
  - numpy
  - pandas
  - scipy
  - seaborn
  - matplotlib
  - scikit-learn
  - r-base
  # -r-tidyverse is not available yet due to upper pin on r-base, and
  # older r-base versions are not available on emscripten-forge, so we
  # install some of the tidyverse packages individually (except for
  # r-lubridate)
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-purrr
  - r-tibble
  - r-stringr
  - r-forcats
  - r-coursekata
  - r-neuralnet
